name: BanSync
author: FireBall1725
url: http://www.craftminecraft.com/

version: ${pom.version}
main: net.craftminecraft.bukkit.bansync.BanSync

database: false
description: Sync player bans to other plugins, such as LWC and PlotMe.

startup: startup

softdepend: [Vault, PlotMe, LWC, GriefPrevention]

commands:
   bansync:
      description: Main command for BanSync.
      usage: /<command> help
   bansync removeuser:
      description: Manually remove user.
      usage: /<command> <username>
   bansync help:
      description: Bansync Help
      usage: /<command> help
      
permissions:
   bansync.removeuser:
      description: Allows you to remove a user manually
      default: op


